name: Build & Deploy to DEV
on:
  push:
    branches: [ master ]
jobs:
  build-and-deploy-dev:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
        
    - name: Build with Maven (dev profile)
      run: mvn clean install -Dspring.profiles.active=dev
      
    - name: Deploy JAR to DEV server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.DEV_SERVER_IP }}
        username: ${{ secrets.DEV_SERVER_USER }}
        key: ${{ secrets.DEV_SERVER_KEY }}
        source: "target/*.jar"
        target: "/home/${{ secrets.DEV_SERVER_USER }}/Library-Application"
        
    - name: Stop existing application
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DEV_SERVER_IP }}
        username: ${{ secrets.DEV_SERVER_USER }}
        key: ${{ secrets.DEV_SERVER_KEY }}
        port: 22
        timeout: 60s
        command_timeout: 2m
        script: |
          echo "Stopping app..."
          timeout 10s pkill -f "Library.*.jar" || true
          echo "Stopped any running application instances"
          
    - name: Start application
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DEV_SERVER_IP }}
        username: ${{ secrets.DEV_SERVER_USER }}
        key: ${{ secrets.DEV_SERVER_KEY }}
        script: |
          cd /home/${{ secrets.DEV_SERVER_USER }}/Library-Application
          # Find the latest JAR file
          JAR_FILE=$(ls -t *.jar | head -1)
          echo "Starting application with JAR file: $JAR_FILE"
          # Use screen to run the application in the background
          nohup java -jar -Dspring.profiles.active=dev "$JAR_FILE" > app.log 2>&1 &
          # Add a sleep to ensure the process starts before the SSH connection closes
          sleep 5
          # Check if process is running
          if pgrep -f "$JAR_FILE" > /dev/null; then
            echo "Application started successfully"
          else
            echo "Failed to start application"
            exit 1
          fi
