name: Build & Deploy to DEV
on:
  push:
    branches: [ master ]
jobs:
  build-and-deploy-dev:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
        
    - name: Build with Maven (dev profile)
      run: mvn clean install -Dspring.profiles.active=dev
      
    - name: Check if JAR was built
      run: |
        ls -la target/
        echo "Looking for JAR files in target directory"
        find . -name "*.jar" | grep -v "original"
        
    - name: Verify Secrets Are Available
      run: |
        if [[ -z "${{ secrets.DEV_SERVER_IP }}" ]]; then
          echo "::error::DEV_SERVER_IP secret is not set or is empty!"
          exit 1
        fi
        
        if [[ -z "${{ secrets.DEV_SERVER_USER }}" ]]; then
          echo "::error::DEV_SERVER_USER secret is not set or is empty!"
          exit 1
        fi
        
        echo "All required secrets appear to be set"
        echo "Server IP length: ${#DEV_SERVER_IP}"
        echo "Server user length: ${#DEV_SERVER_USER}"
        
    - name: Test SSH Connection (Hardcoded Host)
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DEV_SERVER_IP }}
        username: ${{ secrets.DEV_SERVER_USER }}
        key: ${{ secrets.DEV_SERVER_KEY }}
        debug: true
        script: echo "SSH connection successful"
        
    - name: Deploy JAR to DEV server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.DEV_SERVER_IP }}
        username: ${{ secrets.DEV_SERVER_USER }}
        key: ${{ secrets.DEV_SERVER_KEY }}
        source: "target/*.jar"
        target: "/home/${{ secrets.DEV_SERVER_USER }}/Library-Application"
        debug: true
        
    - name: Restart App on DEV server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DEV_SERVER_IP }}
        username: ${{ secrets.DEV_SERVER_USER }}
        key: ${{ secrets.DEV_SERVER_KEY }}
        script: |
          pkill -f "Library.*.jar" || true
          nohup java -jar -Dspring.profiles.active=dev /home/${{ secrets.DEV_SERVER_USER }}/Library-Application/*.jar > /home/${{ secrets.DEV_SERVER_USER }}/Library-Application/app.log 2>&1 &
